FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libbz2-dev liblzma-dev libcurl3-dev libz-dev git build-essential

RUN git clone --recursive https://github.com/samtools/htslib.git

ADD . /repo
WORKDIR /repo
RUN make -j8
